[project]
name = "sudoku-cracker"
version = "1.0.0-beta.1"
description = "Solve any Sudoku puzzle in seconds."
readme = "README.md"
requires-python = "==3.12.3"
dependencies = [
    "kivy>=2.3.1",
    "numpy==2.4.6",
    "pip>=26.1.2",
]

[project.optional-dependencies]
dev = [
    "mypy>=2.1.0",
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "ruff>=0.15.16",
    "buildozer>=1.6.0",
    "cython==0.29.34",
    "setuptools>=82.0.1",
]
ocr = [
    "paddleocr==3.3.3",
    "paddlepaddle==3.2.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.9",
    "opencv-python>=4.13.0.92",
]

[tool.mypy]
ignore_missing_imports = true

[tool.ruff]
exclude = [
    "*.ipynb"
]
