[project]
name = "sudoku-solver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.3"
dependencies = [
    "jupyter>=1.1.1",
    "kivy>=2.3.1",
    "matplotlib>=3.10.9",
    "mypy>=2.1.0",
    "opencv-python>=4.13.0.92",
    "paddleocr==3.3.3",
    "paddlepaddle==3.2.0",
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "ruff>=0.15.16",
]

[tool.mypy]
ignore_missing_imports = true
